version: '2'
services:
  app:
    image: .
    ports:
    - "8080:8080"
    depends_on:
    - database

  database:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres
